In [1]:
import numpy as np
print(np.__version__)


2.5.3


In [8]:
print(np.zeros((2, 3)))
print(np.ones(4))
print(np.size(4))

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
1


In [10]:
marks = np.array([[80, 72, 91],
                  [80, 72, 91],
              [65, 88, 70]])

                
                  