In [1]:
import numpy as np
print(np.__version__)


2.5.3


In [8]:
print(np.zeros((2, 3)))
print(np.ones(4))
print(np.size(4))

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
1


In [1]:
marks = np.array([[80, 72, 91],
                  [80, 72, 91],
              [65, 88, 70]])

                
                  

NameError: name 'np' is not defined

In [5]:
import numpy as np
marks  = np.array([[80, 72, 91],
                  [65, 88, 70],
                  [95, 60, 84]])
print(marks)

[[80 72 91]
 [65 88 70]
 [95 60 84]]


In [22]:
import time

numbers = list(range(1_000_000))
arr = np.array(numbers)

start = time.time()
result = [x * 2 for x in numbers]
print("list :", time.time() - start, "seconds")

start = time.time()
result = arr * 2
print("array :", time.time() - start, "secounds")

list : 0.1476123332977295 seconds
array : 0.040796756744384766 secounds


In [33]:
import numpy as np
print(np.reshape(3, -4))


[3]


In [35]:
import numpy as np
x = np.array([10, 20, 30],dtype=float)
x[0]
x = 15.5
print(x)

15.5


In [42]:
import numpy as np
temps = [
    [30, 32, 31],
    [28, 29, 27]
]
print("karachi temp", temps [0][1] )
print("lahore temp", temps [1][2] )

karachi temp 32
lahore temp 27


In [1]:
import numpy as np
a = np.array([1, 2, 3])

b = a
b[0] = 99

print(a, "/n", b)

[99  2  3] /n [99  2  3]


In [8]:
import pandas as pd
house_numbers = [1002, 1003, 1004, 1005, 1010]


series_data = pd.Series(house_numbers, index=["A1", "A2", "A3", "A4", "A5"])
series_data.info()

<class 'pandas.Series'>
Index: 5 entries, A1 to A5
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 80.0+ bytes


In [ ]:
subjects = pd.DataFrame({
    "math":  [45, 76, 87],
    "physics": [20, 150, 900],
    "english": [100, 40, 12],
})
print(subjects)

AttributeError: module 'pandas' has no attribute 'dataframe'

In [13]:
import pandas as pd

# Run this cell once. It makes the file students.csv
# (an empty place after a comma means the value is missing)
text = """name,age,city,maths,english,science
Ali,16,Lahore,80,72,91
Sara,15,Karachi,65,88,70
Hassan,17,Lahore,95,60,84
Ayesha,16,Islamabad,72,,78
Bilal,15,Karachi,55,64,
Fatima,16,Lahore,88,91,95
Usman,17,Islamabad,,58,62
Zainab,15,Karachi,92,85,89
Hamza,16,Lahore,45,50,48
Maryam,17,Islamabad,78,80,
"""
with open("students.csv", "w") as f:
    f.write(text)

df = pd.read_csv("students.csv")
print(df)

     name  age       city  maths  english  science
0     Ali   16     Lahore   80.0     72.0     91.0
1    Sara   15    Karachi   65.0     88.0     70.0
2  Hassan   17     Lahore   95.0     60.0     84.0
3  Ayesha   16  Islamabad   72.0      NaN     78.0
4   Bilal   15    Karachi   55.0     64.0      NaN
5  Fatima   16     Lahore   88.0     91.0     95.0
6   Usman   17  Islamabad    NaN     58.0     62.0
7  Zainab   15    Karachi   92.0     85.0     89.0
8   Hamza   16     Lahore   45.0     50.0     48.0
9  Maryam   17  Islamabad   78.0     80.0      NaN
